spring.datasource.url=jdbc:mysql://localhost:3306/neartask_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080
app.jwt.secret=neartask_super_secret_key_2024_minimum_32_chars
app.jwt.expiration=86400000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
